#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/mmoa/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

nm-applet &

~/bin/fluxgui &

~/bin/clipit &
# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
xfce4-panel &
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/mmoa/.fluxbox/log"
